name: 'Pull Request'

on:
  pull_request:
    branches:
    - master

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  call-lint:
    uses: ./.github/workflows/_golangci-lint.yml
  call-test:
    uses: ./.github/workflows/_test.yml
  call-swagger-check:
    uses: ./.github/workflows/_swagger-check.yml
  call-styles-check:
    uses: ./.github/workflows/_styles-check.yml
  call-gorelease:
    needs: [call-lint, call-test, call-swagger-check, call-styles-check]
    uses: ./.github/workflows/_gorelease.yml
  call-buildx:
    needs: call-gorelease
    # only build on pull requests from the same repo for now
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/_buildx.yml
